- package-lock.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
The LoaderWrapper component had a gigantic bundle size because it was importing an old version of the Loader component. This PR fixes the Loader version.
`npm install && npm test && npm run spec`. Also `npm run build` and verify that sling-web-component-loader-wrapper/dist/iife/es6/index.js doesn't have 43,000+ lines!
The bundle should have about 6.000+ lines. It will be improved when we resolve the way moment is imported.
> Fix LoaderWrapper's gigantic bundle size

- packages/sling-web-component-card/src/component/Card.js
- packages/sling-web-component-card/src/component/Card.test.js
It resolves the unexpected behavior reported in issue #71 . Now the Card component hiddes the empty slots.  
- Now this component use the variable isVisible in "applySlotClass" function
- Changed the usage of function "applySlotClass" to be consistent with parameter hasPadding
- Added unit tests to function "applySlotClass"
> Hides empty slots in Card component

- lerna.json
Now the packages can have each a different version, automated by semantic release. We need this change on Lerna to work properly.
- Changes lerna.json contents
> CMPDC-1019: Updates Lerna

- .gitignore
- packages/sling-web-component-input/src/component/Input.js
Now the mask work as expected, no matter how many digits a phone have
> fix(sling-input): Phone Mask issue

- packages/sling-web-component-brand-icon/README.md
- packages/sling-web-component-button/README.md
- packages/sling-web-component-calendar/README.md
- packages/sling-web-component-card/README.md
- packages/sling-web-component-form/README.md
- packages/sling-web-component-icon/README.md
- packages/sling-web-component-input/README.md
- packages/sling-web-component-label/README.md
- packages/sling-web-component-list/README.md
- packages/sling-web-component-loader-wrapper/README.md
- packages/sling-web-component-loader/README.md
- packages/sling-web-component-login/README.md
- packages/sling-web-component-message/README.md
- packages/sling-web-component-paginator/README.md
- packages/sling-web-component-sdk-connect/README.md
- packages/sling-web-component-select/README.md
- packages/sling-web-component-snackbar/README.md
- packages/sling-web-component-table/README.md
- packages/sling-web-component-tooltip/README.md
Command line typos.
fixes #109 
- To fix the spelling of the word "install" in components' guides.
> Fix typos on documentation

- packages/sling-framework/src/v1/src/business/withLoadingAndErrorHandling.js
When using `withRequest` on new business components, eventual request errors won't be cleaned after trying a new request. This PR fixes that.
> Clean previous request errors when making a new request

- package.json
A short fix to enable semantic release on the `master` branch instead of the `next` branch
> [develop] fix: Enable semantic release on master

- package.json
Short description of what this resolves:
A short fix to enable semantic release on the master branch instead of the next branch
> [master] fix: Enable semantic release on master

- packages/emd-basic-button/package.json
- packages/emd-basic-button/public/index.css
- packages/emd-basic-button/public/index.html
- packages/emd-basic-button/public/index.js
- packages/emd-basic-button/src/component/Button.css
- packages/emd-basic-button/src/component/ButtonController.js
- Fixes the bug that would prevent the Button to be clicked on IE Edge.
- Adds "Button With Icon" example.
- Prevents the `click` event from being dispatched while the Button is either disabled or loading.
```
npm install && npm test && npm start emd-basic-button
```
> Fix Button on Edge and prevent unwanted `click` events

- packages/emd-basic-button/src/component/Button.css
Fix bug that causes Buttons to be unclickable when shadow DOM polyfills are used.
> Fix bug that causes Buttons to be unclickable on Edge

- packages/sling-web-component-card/src/component/Card.js
- packages/sling-web-component-card/src/component/Card.test.js
This PR fixes the legacy (Sling) Card so that when header, body or footer content is added, the Card displays the new information correctly.
- Run:
```
npm install
npm start sling-web-component-card
```
- Inspect the first Card element on the page
- Right-click the element's tag and select `Edit HTML`
- Add a new `div` with any content in the Card element
- The new content should appear in the Card's body
> Make Card behave correctly when children are updated

- CHANGELOG.md
- packages/sling-web-component-table/src/assets/Table.css
- packages/sling-web-component-table/src/component/Table.js
- packages/sling-web-component-table/src/component/Table.test.js
Substitute `.emd-table` CSS class for `.emd-table__wrapper` to avoid conflicts with the web components polyfill used by Edge.
To test:
```
npm install && npm start sling-web-component-table
```
> Fix – legacy Sling Table

- package-lock.json
- packages/emd-basic-money-card/public/index.css
- packages/emd-basic-money-card/src/component/MoneyCard.css
This PR removes the margin of slotted elements as it is being applied incorrectly on the Dashboard on Ie Edge, and it's not being used in Portal anymore.
> Fix – Remove slotted margin

- packages/emd-basic-card/src/component/Card.css
- packages/emd-basic-card/src/component/CardController.js
- packages/emd-basic-card/src/component/CardView.js
This PR adds the `noscroll` property to the Card that forces it not to have a scrollbar.
I did this because I want the scrollbar to be State Wrapper's responsibility in some cases.
```html
<emd-card noscroll>
<emd-state-wrapper>
<emd-some-business></emd-some-business>
<emd-state-wrapper>
</emd-card>
```
To test:
```
npm install
npm test
```
> Feature – Add noscroll property to Card

- packages/emd-basic-state-wrapper/package-lock.json
- packages/emd-basic-state-wrapper/package.json
- packages/emd-basic-state-wrapper/public/index.html
- packages/emd-basic-state-wrapper/public/index.js
- packages/emd-basic-state-wrapper/public/rows.js
- packages/emd-basic-state-wrapper/src/component/StateWrapper.css
- packages/emd-basic-state-wrapper/src/component/StateWrapperController.js
- packages/emd-basic-state-wrapper/src/component/StateWrapperView.js
- packages/emd-basic-state-wrapper/src/component/helpers/getViewCssVariant.js
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperEmpty.css
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperEmptyView.js
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperError.css
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperErrorView.js
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperPristine.css
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperPristineView.js
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperRecovery.css
- packages/emd-basic-state-wrapper/src/component/views/StateWrapperRecoveryView.js
This PR adds new features to the State Wrapper basic component that were long overdue, and yet, doesn't introduce any breaking changes:
- Add a compact `view` property that makes the component display smaller error messages;
- Default:
- Compact:
- Parameterize Error and Recovery text and icon colors;
- Default (always red):
- Custom (any color):
- Allow the `recovery` action to be passed as a parameter (before, it was always `buildSource`);
```html
<emd-state-wrapper>
<emd-some-business></emd-some-business>
</emd-state-wrapper>
```
```js
const wrapper = document.querySelector('emd-state-wrapper');
const business = document.querySelector('emd-some-business');
wrapper.recovery = business.buildInput.bind(business);
```
- Make sure that the component won't break if empty;
```html …
```
> Task – State Wrapper improvements

- .eslintrc
- packages/emd-basic-state-wrapper/src/component/StateWrapperView.js
This PR allows the `recovery` property to be passed as a String.
If it is a Function, it will be executed in recovery mode (like when a request fails).
If it is a String, a method with the same name will be exectuded for recovery.
If nothing is passed, the recovery method defaults to `buildSource` (the original behaviour).
New tests were added:
```
npm install
npm test
```
> Feature – Allow recovery to be passed as a String

- packages/emd-basic-brand-icon/src/component/BrandIconView.js
The world's smallest PR.
Yes, this `;` breaks the component on Edge.
> Fix component on IE Edge

- package-lock.json
- packages/emd-basic-field/package-lock.json
- packages/emd-basic-field/package.json
- packages/emd-basic-field/public/index.css
- packages/emd-basic-field/public/index.html
- packages/emd-basic-field/src/component/FieldController.js
- packages/emd-basic-field/src/core.js
- packages/emd-basic-field/src/helpers/maskMaker.js
- packages/emd-basic-field/src/hocs/withFieldType.js
- packages/emd-basic-field/src/types/billet/maskBillet.js
- packages/emd-basic-field/src/types/billet/validateBillet.js
- packages/emd-basic-field/src/types/billet/validateBillet.spec.js
- packages/emd-basic-field/src/types/cep/maskCep.js
- packages/emd-basic-field/src/types/cnpj/maskCnpj.js
- packages/emd-basic-field/src/types/cpf/maskCpf.js
- packages/emd-basic-field/src/types/money/maskMoney.js
- packages/emd-basic-field/src/types/tel/maskTel.js
This PR changes the library we use for masking inputs from [CleaveJS](https://nosir.github.io/cleave.js/) to the more powerful [iMaskJS](https://imask.js.org/).
It made possible to create masks that change dynamically during typing:
- Phone masks now can have either `(00) 0000-0000` or `(00) 00000-0000` formats;
- There's a new field type for barcodes which also changes dynamically while typing.
I wanted to make the money field always consider decimals, like the value was being divided by 100, but I could not figure out how to do it this time.
```
npm install
npm start emd-basic-field
```
```
npm install
npm test
```
I did test the component on IE Edge using browser stack.
> Feature – iMask and Billet field type

- packages/emd-basic-field/package-lock.json
- packages/emd-basic-field/package.json
- packages/emd-basic-field/src/types/billet/validateBillet.spec.js
- packages/emd-basic-loader/package-lock.json
- packages/emd-basic-loader/package.json
- packages/emd-basic-loading-wrapper/package-lock.json
- packages/emd-basic-loading-wrapper/package.json
- packages/emd-basic-loading-wrapper/public/index.css
- packages/emd-basic-loading-wrapper/public/index.html
- packages/emd-basic-loading-wrapper/public/index.js
- packages/emd-basic-loading-wrapper/src/component/LoadingWrapper.css
- packages/emd-basic-loading-wrapper/src/component/LoadingWrapperController.js
- packages/emd-basic-loading-wrapper/src/component/LoadingWrapperView.js
- packages/emd-basic-loading-wrapper/src/core.js
- packages/emd-basic-loading-wrapper/src/index.js
- packages/emd-basic-select/package-lock.json
- packages/emd-basic-select/package.json
State Wrapper was designed to handle loading events, errors and empty sources. Except for some intrusive CSS, it works ok, but also tries do to too much.
This new component, Loading Wrapper, specializes in dealing with the loading state only. It shows a spinner and fades the child component if it is loading.
It also has a new property, called `screenaware`, that allows the spinner to always be visible inside the component even if it is cropped by the viewport.
Some visual aspects are configurable via CSS properties: `--emd-loading-wrapper-opacity`, `--emd-loading-wrapper-transition-speed` and `--emd-loading-wrapper-opacity`.
```
npm install
npm run emd-basic-loading-wrapper
```
> Feature – Loading Wrapper component

- package-lock.json
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-brand-icon/src/component/BrandIcon.css
Upgrades minimum `emd-assets` version on brand icon basic component and adds style options to the new brands.
> Feature/portal 79780 Add more brands to brand icon

- packages/emd-basic-brand-icon/src/component/BrandIcon.css
Fix Sorocred icon sizes and adjust some others.
Before:
After:
> Fix – Brand Icon logo sizes

- packages/emd-basic-table/src/component/TableController.js
- packages/emd-basic-table/src/component/TableController.spec.js
Restrict `rowclick` events to clickable rows
> Hot Fix – Restrict rowclick events to clickable rows [MASTER]

- packages/emd-basic-field/public/index.css
- packages/emd-basic-field/public/index.html
- packages/emd-basic-field/src/core.js
- packages/emd-basic-field/src/types/bankAccount/maskBankAccount.js
- packages/emd-basic-field/src/types/integer/maskInteger.js
Add two new input types, `bank-account` and `integer`.
```html
<emd-field type="bank-account"></emd-field>
```
```html
<emd-field type="integer"></emd-field>
```
```
npm install
npm test
```
```
npm install
npm start emd-basic-field
```
> feat: Add two new input types: `bank-account` and `integer`

- packages/emd-basic-loading-wrapper/src/component/LoadingWrapperController.js
Prevent component from breaking if its child is removed from the DOM.
````
npm i && npm t
```
```
npm i && npm start emd-basic-loading-wrapper
```
> Hot Fix – Prevent component from breaking if its child is removed from the DOM

- packages/emd-basic-select/src/component/Select.css
Fix Select text overflow.
```
npm i && npm t
```
```
npm i && npm start emd-basic-select
```
> Fix – Correct text overflow on Select

- packages/emd-basic-field-wrapper/src/component/FieldWrapperController.js
This PR allows Field Wrapper to listen to Fields wrapped in other tags. This will work:
```html
<emd-field-wrapper>
<div>
<emd-field name="user" type="text" required></emd-field>
</div>
</emd-field-wrapper>
```
```
npm i && npm t
```
```
npm i && npm start emd-basic-field-wrapper
```
> fix: Allow Field Wrapper to listen to Fields wrapped in other tags

- packages/emd-basic-field/src/component/FieldView.js
- packages/emd-basic-select/src/component/SelectController.js
- packages/emd-basic-select/src/component/SelectView.js
- On Field and Select, prevent the validation icon from being hidden when `hideicon` is on.
- On Select, prevents user interaction via keyboard keys (except Tab) when component is `readonly`
```
npm i && npm t
```
```
npm i && npm start emd-basic-field
npm i && npm start emd-basic-select
```
> Fix – hideicon and readonly

- packages/emd-basic-button/src/component/ButtonController.js
- packages/emd-basic-button/src/component/ButtonView.js
Guarantees that the `click` event will one be dispatched once if the button is clicked multiples times in sequence.
This default behavior can be disabled by using `multipleclicks`.
```
npm i && npm t
```
```
npm i && npm start emd-basic-button
```
> Feature — Button click debounce

- packages/emd-basic-icon/package-lock.json
- packages/emd-basic-icon/package.json
Update the package `emd-assets` to rename `delete` to `remove-circle` and fix `add-circle`.
```
npm i && npm start emd-basic-icon
```
> Hotfix — Rename delete to remove-circle and fix add-circle

- packages/emd-basic-field-wrapper/public/index.css
- packages/emd-basic-field-wrapper/src/component/FieldWrapper.css
Correct margin of error messages with two or more lines
```
npm i && npm start emd-basic-field-wrapper
```
> Hotfix — Correct margin of error messages with two or more lines

- packages/emd-basic-field-wrapper/src/component/FieldWrapper.css
I shouldn't have killed this `min-height`.
```
npm i && npm start emd-basic-field-wrapper
```
> Hotfix — Redo emptyhint min-height

- packages/emd-basic-field-wrapper/src/component/FieldWrapper.css
- packages/emd-basic-field-wrapper/src/component/FieldWrapperView.js
This PR fixes the way the height of the empty error message is calculated, so that showing and hiding and error won't make the content below moves.
Note how the content below the field slightly moves up and down when the error message is shown or hidden.
```
npm i && npm t
```
```
npm i && npm start emd-basic-field-wrapper
```
> Hotfix — Fix the height of the empty error message

- packages/emd-basic-field/src/component/Field.css
- packages/emd-basic-select/src/component/Select.css
Form fields with `type=hidden` are not actually being hidden because `display: none` set to the `:host` can be changed from the outside, which the Field Wrapper component does.
Change the field of any type to `hidden` and it should disappear.
```
npm i && npm start emd-basic-form
```
> Hotfix — Correct "type=hidden" visibility

- .storybook/config.js
- packages/emd-basic-button/README.md
- packages/emd-basic-button/src/component/Button.stories.js
This PR adds Storybook and Readme documentation for the Emerald Button.
Please read, try and see if you can spot any mistakes!
```
npm i && npm t
```
```
```
```
npm i && npm start emd-basic-button
```
> Feature — Add Storybook and Readme documentation for the Emerald Button

- .storybook/config.js
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-login/src/component/Login.stories.js
- packages/emd-basic-money/README.md
- packages/emd-basic-money/src/component/Money.stories.js
Add README and Storybook for Money
```
npm i && npm t
```
```
```
```
npm i && npm start emd-basic-money
```
> Feature — Add README and Storybook for Money

- .storybook/config.js
- .storybook/style.css
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-card/src/component/Card.stories.js
- packages/emd-basic-login/src/component/Login.stories.js
- packages/emd-basic-money/src/component/Money.stories.js
Improve Storybook documentation by adding dynamic code samples next to the components.
```
npm i && npm t
```
```
npm run storybook
```
> Feature — Add code samples to Storybook

- packages/emd-basic-field/src/component/Field.css
- packages/emd-basic-select/src/component/Select.css
Keep `display: none` along with newer CSS
> Fix — Keep `display: none` along with newer CSS

- packages/emd-basic-brand-icon/src/component/BrandIcon.css
- packages/emd-basic-brand-icon/src/component/BrandIconController.js
- packages/emd-basic-brand-icon/src/component/BrandIconView.js
By default, unknown brands fallback to Stone. This PR adds a property called `nofallback` that makes the component display nothing instead.
```
npm i && npm t
```
```
npm i && npm start emd-basic-brand-icon
```
> Feature — nofallback property

- packages/emd-basic-icon/src/component/Icon.stories.js
Add missing `"` to HTML sample on Icon's Storybook.
```
```
> Fix sample HTML output

- .storybook/config.js
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-card/src/component/Card.stories.js
- packages/emd-basic-icon/src/component/Icon.stories.js
- packages/emd-basic-login/src/component/Login.stories.js
- packages/emd-basic-money/src/component/Money.stories.js
- packages/emd-basic-tooltip/README.md
- packages/emd-basic-tooltip/public/index.css
- packages/emd-basic-tooltip/public/index.html
- packages/emd-basic-tooltip/src/component/Tooltip.css
- packages/emd-basic-tooltip/src/component/Tooltip.stories.js
- packages/emd-basic-tooltip/src/component/TooltipController.js
- packages/emd-basic-tooltip/src/component/TooltipView.js
This PR makes a radical change in the way the Tooltip is used and how it is positioned on screen. Although it seems to not have changed, the component doesn't wrap the target anymore, which:
- Prevents a bug that would cause unwanted scrollbars to appear while the tooltip is visible;
- Allows the tooltip to have any complex markup inside it, instead of just a string.
Please note that, for compatibility reasons, the legacy mark-up still works if the tooltip doesn't receive a `for` property, but only the new mark-up is documented.
```html
<emd-tooltip text="Some tooltip information">
<p>Target element</p>
</emd-tooltip>
```
```html
<p id="target">Target element</p>
<emd-tooltip for="target">
Some <em>tooltip</em> information.
</emd-tooltip>
```
This PR also adds new CSS properties and HTML …
> Feature — Enhance Tooltip component (and fixes a bug)

- packages/emd-basic-notification/public/index.html
Add example with two buttons just to test the CI.
> Fix — Add example with two buttons

- packages/emd-basic-notification/public/index.css
- packages/emd-basic-notification/public/index.html
- packages/emd-basic-notification/src/component/Notification.css
- packages/emd-basic-notification/src/component/NotificationController.js
- packages/emd-basic-notification/src/component/NotificationView.js
- packages/emd-basic-notification/src/core.js
Fixes a layout problem when multiple children were added to any slot.
```
npm i && npm t
```
```
npm i && npm start emd-basic-notification
```
> Hotfix — Slots with multiple children

- packages/emd-basic-slideshow/README.md
- packages/emd-basic-slideshow/src/component/Slideshow.css
- packages/emd-basic-slideshow/src/component/Slideshow.stories.js
- packages/emd-basic-slideshow/src/component/SlideshowController.js
- packages/emd-basic-slideshow/src/component/SlideshowController.spec.js
- packages/emd-basic-slideshow/src/component/SlideshowView.js
- packages/emd-basic-tooltip/src/component/TooltipController.js
- packages/emd-basic-tooltip/src/component/TooltipView.js
- Implements `--emd-slideshow-gap` CSS property to control the gap between slides
- Dispatches `slidechange` (alias: `slidechangestart`) when the current slide changes, just before the animation begins.
- Dispatches `slidechangeend` after the current slide changes and the animation ends.
The PR also moves the responsibility of changing the `delay` property from the Controller to the View on both Tooltip and Slideshow components.
```
npm i && npm t
```
```
npm i && npm start emd-basic-slideshow
```
```
```
> Feat — Slideshow gap and events

- .github/CODEOWNERS
- .github/workflows/deploy-docs.yml
- CODEOWNERS
- CONTRIBUTING.md
- README.md
`emd-master` no longer exists.
This PR removes references to `emd-master` in the documentation.
> Feature — Remove references to emd-master [MASTER]

- .github/CODEOWNERS
- .github/workflows/deploy-docs.yml
- CODEOWNERS
- CONTRIBUTING.md
- README.md
`emd-master` no longer exists.
This PR removes references to `emd-master` in the documentation.
> Feature — Remove references to emd-master [DEVELOP]

- packages/emd-basic-brand-icon/src/component/BrandIconController.js
- packages/emd-basic-brand-icon/src/component/BrandIconController.spec.js
- packages/emd-basic-bullet/src/component/BulletController.js
- packages/emd-basic-card/src/component/CardController.js
- packages/emd-basic-date/src/component/DateController.js
- packages/emd-basic-drawer/src/component/DrawerController.js
- packages/emd-basic-feature/src/component/FeatureController.js
- packages/emd-basic-field-message/src/component/FieldMessageController.js
- packages/emd-basic-field-wrapper/src/component/FieldWrapperController.js
- packages/emd-basic-field/src/component/FieldController.js
- packages/emd-basic-form/src/component/FormController.js
- packages/emd-basic-icon/src/component/IconController.js
- packages/emd-basic-loader/src/component/LoaderController.js
- packages/emd-basic-loan-success-dialog/src/component/LoanSuccessDialogController.js
- packages/emd-basic-login/src/component/LoginController.js
- packages/emd-basic-money-card/src/component/MoneyCardController.js
- packages/emd-basic-money-promo/src/component/MoneyPromoController.js
- packages/emd-basic-money/src/component/MoneyController.js
- packages/emd-basic-money/src/component/MoneyController.spec.js
- packages/emd-basic-pill/src/component/PillController.js
- packages/emd-basic-select/src/component/SelectController.js
- packages/emd-basic-simulator-result/src/component/SimulatorResultController.js
- packages/emd-basic-state-wrapper/src/component/StateWrapperController.js
- packages/emd-basic-table/src/component/TableController.js
- packages/emd-basic-table/src/component/TableController.spec.js
The method `currentView.apply` was deprecated in favor of `currentView.use` a long time ago because `.apply()` is a method of `Function`.
This PR substitutes all `currentView.apply` used in components for `currentView.use`.
```
npm i && npm t
```
```
```
> fix: Substitute deprecated currentView.apply for currentView.use
