- .travis/after_success.sh
- CHANGELOG.md
- lerna.json
- package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
<a name="1.0.1"></a>
* fix: deployment script ([f78d965](https://github.com/stone-payments/sling-framework/commit/f78d965))
> Hotfix: v1.0.1

- CHANGELOG.md
- lerna.json
- package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-helpers/src/sdk/onSdkAccessible.js
<a name="1.0.2"></a>
* fix: sdk connect ([6bf9233](https://github.com/stone-payments/sling-web-framework/commit/6bf9233))
> Hotfix: v1.0.2

- CODEOWNERS
- package-lock.json
- packages/sling-helpers/src/global/globalHelper.js
- packages/sling-helpers/src/global/globalHelper.spec.js
Update helpers code to add new function that existed on the previous project.
Running unit tests.
> update helpers code

- CHANGELOG.md
- README.md
- lerna.json
- package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
<a name="1.1.0"></a>
* feat: add getDateRangeArray to helpers ([350e703](https://github.com/stone-payments/sling-web-framework/commit/350e703))
* feat: update travis.yml ([c444f91](https://github.com/stone-payments/sling-web-framework/commit/c444f91))
* feat: add unit tests coverage ([487b297](https://github.com/stone-payments/sling-web-framework/commit/487b297))
> Release: v1.1.0

- CHANGELOG.md
- lerna.json
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-snackbar/package.json
> [DEVELOP] Release/v1.3.0

- packages/sling-web-component-select/.npmignore
- packages/sling-web-component-select/README.md
- packages/sling-web-component-select/index.js
- packages/sling-web-component-select/package-lock.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-select/public/index.css
- packages/sling-web-component-select/public/index.html
- packages/sling-web-component-select/src/assets/Select.css
- packages/sling-web-component-select/src/assets/host.css
- packages/sling-web-component-select/src/component/Select.js
- packages/sling-web-component-select/src/component/Select.test.js
- packages/sling-web-component-select/src/index.css
- packages/sling-web-component-select/src/index.js
This PR brings `Select` component from the sling-web repository.
By running `npm install && npm rebuild && npm test && npm run spec`. Also by starting the components with `npm start sling-web-component-select`
⚠️ This is a subtask from CMPDC-905
> CMPDC- 934: Moves Select component from sling-web

- CHANGELOG.md
- package-lock.json
- package.json
* feat: Brings Message component from `sling-web` ([3e6d3dc](https://github.com/stone-payments/sling-web-framework/commit/3e6d3dc))
* feat: Brings Input component from `sling-web` ([5ee4858](https://github.com/stone-payments/sling-web-framework/commit/5ee4858))
* feat: Brings Select component from `sling-web` ([29f4902](https://github.com/stone-payments/sling-web-framework/commit/29f4902))
* feat: Moved Card and Table component from `sling-web` ([c30c8b5](https://github.com/stone-payments/sling-web-framework/commit/c30c8b5))
* feat: Moved Loader and Loader Wrapper from `sling-web` ([f4240d1](https://github.com/stone-payments/sling-web-framework/commit/f4240d1))
* feat: Moved Calandar and Paginator from `sling-web` ([a6578e4](https://github.com/stone-payments/sling-web-framework/commit/a657 …
> [develop] Release 1.4.0

- CHANGELOG.md
- lerna.json
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
> Release/v1.5.0 – Develop

- CHANGELOG.md
- lerna.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
> Release/v1.7.0 – Develop

- CHANGELOG.md
- lerna.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
> Release/v1.7.0 – Master

- README.md
- Update README.md contribute link.
open README.md and check the contribuite link.
> Issue #59 - Update README.md contribute link.

- packages/sling-framework/src/index.js
- packages/sling-framework/src/v1/src/index.js
There is a new component that needs to manage requests and a loading visualization.
- Exported the withLoading class.
> PRTME-6: Adjustment for using on components

- CHANGELOG.md
- lerna.json
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
Generate new release version 1.8.0
[CHANGELOG.md](https://github.com/stone-payments/sling-web-framework/blob/release/1.8.0/CHANGELOG.md)
> [MASTER] Release/1.8.0

- CHANGELOG.md
- lerna.json
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
Generate new release version 1.8.0
[CHANGELOG.md](https://github.com/stone-payments/sling-web-framework/blob/release/1.8.0/CHANGELOG.md)
> [DEVELOP] Release/1.8.0

- package-lock.json
- package.json
- packages/sling-helpers/package-lock.json
- packages/sling-web-component-calendar/package-lock.json
- packages/sling-web-component-input/package-lock.json
- packages/sling-web-component-table/package-lock.json
Fix #4 
- npm install package.json
- npm update lerna
- npm tests
All seems to be working as expected. But I have no context on extra necessary validation.
> Upgrade Lerna to 3.4.1

- .github/CONTRIBUTING.md
Add a better explanation about how to commit
> CMPDC-1020: Update contributing for semanting-release

- package-lock.json
- packages/sling-web-component-label/.npmignore
- packages/sling-web-component-label/README.md
- packages/sling-web-component-label/package-lock.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-label/public/index.css
- packages/sling-web-component-label/public/index.html
- packages/sling-web-component-label/src/assets/Label.css
- packages/sling-web-component-label/src/component/Label.js
- packages/sling-web-component-label/src/component/Label.test.js
- packages/sling-web-component-label/src/index.css
- packages/sling-web-component-label/src/index.js
> cmpdc 1023: Label component

- package.json
Adds back (temporarily) lerna commands to release
> chore: Lerna Release

- packages/sling-web-component-card/src/component/Card.js
change Card header background color using `backgroundHeader` attribute
> feat: change Card header background color

- scripts/build.js
CSS injection was setted for only run on CI, this PR fix it
> [hotfix] Fix css injection

- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
- scripts/build.js
> Sync master and develop

- nightwatch.json
- package-lock.json
- package.json
- scripts/night.js
now we can run `npm run nightwatch component-name` to run nightwatch tests
> feature: Nightwatch Script

- nightwatch.json
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-brand-icon/src/component/BrandIcon.regression.test.js
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
- scripts/build.js
- scripts/night.js
Adds regression test for sling brand icon
Take brand icon screenshots
the first time run `npm run e2e:setup`
to executre the tests run `npm run nightwatch`
> Sling brand icon regression tests 

- packages/sling-web-component-select/src/component/Select.regression.test.js
fiz caca e apaguei o arquivo sem querer
vai na fé e aprova
> Select regression test

- package-lock.json
- packages/sling-web-component-card/README.md
- packages/sling-web-component-card/public/index.html
- packages/sling-web-component-card/src/assets/Card.css
- packages/sling-web-component-card/src/component/Card.js
- packages/sling-web-component-card/src/component/Card.test.js
This PR makes the component react to the dynamic inclusion or exclusion of a header, a body or a footer, fixing a bug that made these parts always invisible if they were set dynamically, after the component was already rendered.
It also adds the ability to show or hide the divisors between the header, the body and the footer.
The image below shows the card:
* with divisors and padding
* without divisors and with padding
* with divisors and without padding
* without divisors and padding
> CMPDC-1046 – Update Card Component

- .travis.yml
- package.json
- packages/sling-helpers/src/global/globalFormatters.js
- packages/sling-helpers/src/global/globalHelper.js
- packages/sling-web-component-calendar/src/component/Calendar.js
- packages/sling-web-component-calendar/src/component/Calendar.test.js
- scripts/build.js
Makes moment explicitly import pt-BR localization files.
Corrects the build so that it only injects CSS into files in the src folder on npm distribution (but never not locally).
> CMPDC-1051 – Correct moment localization

- .eslintrc
- CHANGELOG.md
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-select/src/component/Select.regression.test.js
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
> Release/1.11.5 – Develop

- CHANGELOG.md
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
> Release/1.11.6 – Develop

- .gitignore
- .travis.yml
- sonar-project.properties
> chore: add sonar cloud

- packages/sling-web-component-button/src/assets/Button.css
Adds the following customizations for sling button:
- Background color
- Text color
- Border color
- Darken color when the button is clicked
Added the following css attributes
- --sling-button-border-color
- --sling-button-background-color
- --sling-button-text-color
> Button customizations

- packages/sling-web-component-button/src/assets/Button.css
- packages/sling-web-component-input/src/assets/Input.css
- packages/sling-web-component-loader/src/assets/Loader.css
- packages/sling-web-component-paginator/src/assets/Paginator.css
- packages/sling-web-component-select/src/assets/Select.css
The primary color should be changed from `#95C93D` to `#0DB14B`
The color was changed on all the places thats uses`#95C93D` to `#0DB14B`
The button primary active color was changed to `#0C9141` to match the new color
> Changes Primary color 

- CHANGELOG.md
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
> [develop] Release/1.11.7

- packages/sling-assets/src/icons/index.js
- packages/sling-assets/src/icons/js/ellipsis.js
- packages/sling-assets/src/icons/svg/ellipsis.svg
- packages/sling-web-component-icon/public/index.html
- packages/sling-web-component-icon/src/component/Icon.js
- packages/sling-web-component-icon/src/component/Icon.test.js
This PR adds a new icon to Sling Icon component.
**Tests should be added!**
> CMPDC-1120 – Add ellipsis icon to Sling Icon component

- package-lock.json
- packages/sling-web-component-table/public/index.html
- packages/sling-web-component-table/src/assets/Table.css
- packages/sling-web-component-table/src/assets/host.css
- packages/sling-web-component-table/src/component/Table.js
https://stonepayments.atlassian.net/browse/CMPDC-1101
Should look like this: https://zpl.io/VqKm3y5
> [CMDPC-1101] Refreshs Table Layout

- package-lock.json
- packages/sling-helpers/package-lock.json
- packages/sling-helpers/package.json
- packages/sling-helpers/src/dom/domHelper.js
- packages/sling-helpers/src/dom/domHelper.test.js
- packages/sling-helpers/src/global/globalHelper.js
- packages/sling-helpers/src/global/globalHelper.spec.js
- packages/sling-web-component-calendar/package-lock.json
- packages/sling-web-component-input/package-lock.json
- packages/sling-web-component-table/package-lock.json
Add news helpers to Sling Helpers.
**Tests should be created!**
Adds the following helpers to Sling Helpers:
A promise that waits for a given time in milliseconds before resolving:
```javascript
sleep(1000).then(continue);
```
Similar to [Lodash `set`](https://lodash.com/docs/#set), except it's written using the functional paradigm.
Similar to [Lodash `get`](https://lodash.com/docs/#get), except it's written using the functional paradigm.
Checks if **all** nested properties of an object or array are either null or undefined.
```javascript
const test = { a: null, b: undefined, c: [], d: [null, undefined], e: { e1: null, e2: [null, undefined] } }
isDeeplyEmpty(test); // true
```
Merge arrays excluding repeated values.
```javascript
mergeUnique([1, 2, 3], [2, 3, 4], [3, 4, 5]); // [1, 2, 3, …
```
> CMPDC-1121 – Add news helpers to Sling Helpers

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/snackbar/SnackbarDanger.js
- storybook/stories/snackbar/SnackbarNormal.js
- storybook/stories/snackbar/SnackbarSuccess.js
- storybook/stories/snackbar/SnackbarWarning.js
- storybook/stories/snackbar/snackbar.stories.js
> feat: Add snackbar storybook

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/paginator/Paginator.js
- storybook/stories/paginator/paginator.stories.js
- Adds paginator component to storybook
> feat: Add paginator component to storybook

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/calendar/Calendar.js
- storybook/stories/calendar/calendar.stories.js
- Adds calendar component to storybook
> feat: Add calendar component to storybook

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/card/Card.js
- storybook/stories/card/card.stories.js
- Add card component to storybook
> feat: Add card component to storybook

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/loader/Loader.js
- storybook/stories/loader/loader.stories.js
- Adds loader component to storybook
> feat: Add loader component to storybook

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/login/Login.js
- storybook/stories/login/login.stories.js
- Adds login component to storybook
> feat: Add login component to storybook

- storybook/package.json
- storybook/stories/icon/IconClose.js
- storybook/stories/icon/IconDanger.js
- storybook/stories/icon/IconInfo.js
- storybook/stories/icon/IconSuccess.js
- storybook/stories/icon/IconWarning.js
- storybook/stories/icon/icon.stories.js
- adds icon component storybook
> feat: add icon storybook

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/table/Table.js
- storybook/stories/table/TableClickableRows.js
- storybook/stories/table/TableEditable.js
- storybook/stories/table/TableNoHeader.js
- storybook/stories/table/table.stories.js
>  feat: add table stories

- storybook/package-lock.json
- storybook/package.json
- storybook/stories/message/MessageAlert.js
- storybook/stories/message/MessageError.js
- storybook/stories/message/MessageStandby.js
- storybook/stories/message/MessageSuccess.js
- storybook/stories/message/message.stories.js
-  adds message stories on storybook
> [cmpdc 1138] adds message stories

- README.md
- storybook/package.json
- adds Storybook link to README
- adds storybook build script to `package.json`
> [cmpdc 1144] Storybook on README

- CHANGELOG.md
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-field-message/package.json
- packages/sling-web-component-field/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-menu-item/package.json
- packages/sling-web-component-menu/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
> Release/v1.12.1 – Develop

- packages/sling-web-component-form/src/hoc/withForm.js
- packages/sling-web-component-form/src/hoc/withForm.test.js
This PR fixes a conflict that would happen if a web page ran versions 1.x and 2.x of the form component.
Basically, version 2.x expects `sling-form` not to be defined in the DOM and a conflict would happen if it was.
To test, run `npm run test`. New tests were added.
> Fix conflict with older form version

- CHANGELOG.md
- packages/sling-assets/package.json
- packages/sling-web-component-icon/package.json
Adding Bar Code Icon to _sling-assets_ and using in _sling-web-component-icon_
Version of packages has been updated as minor.
-
-
-
> Release/sling icon 

- packages/sling-web-component-table/src/component/Table.test.js
> Add test to rate

- CHANGELOG.md
- package-lock.json
- packages/sling-web-component-table/package.json
> Release/v2.2.0 - Develop

- CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Add CONTRIBUTING.md [EMD-MASTER]
> Add CONTRIBUTING.md [EMD-MASTER]

- packages/emd-basic-button/CHANGELOG.md
- packages/emd-basic-button/package-lock.json
- packages/emd-basic-button/package.json
- packages/emd-basic-loader/CHANGELOG.md
- packages/emd-basic-loader/package-lock.json
- packages/emd-basic-loader/package.json
> Release – Button

- packages/emd-basic-button/src/component/Button.css
> Release – Button v1.1.1

- CHANGELOG.md
- package-lock.json
- package.json
- packages/sling-assets/package.json
- packages/sling-framework/package.json
- packages/sling-helpers/package.json
- packages/sling-web-component-brand-icon/package.json
- packages/sling-web-component-button/package.json
- packages/sling-web-component-calendar/package.json
- packages/sling-web-component-card/package.json
- packages/sling-web-component-field-message/package.json
- packages/sling-web-component-field/package.json
- packages/sling-web-component-form/package.json
- packages/sling-web-component-icon/package.json
- packages/sling-web-component-input/package.json
- packages/sling-web-component-label/package.json
- packages/sling-web-component-list/package.json
- packages/sling-web-component-loader-wrapper/package.json
- packages/sling-web-component-loader/package.json
- packages/sling-web-component-login/package.json
- packages/sling-web-component-menu-item/package.json
- packages/sling-web-component-menu/package.json
- packages/sling-web-component-message/package.json
- packages/sling-web-component-paginator/package.json
- packages/sling-web-component-sdk-connect/package.json
- packages/sling-web-component-select/package.json
- packages/sling-web-component-snackbar/package.json
- packages/sling-web-component-table/package.json
- packages/sling-web-component-tooltip/package.json
> Release/2.3.0 – Develop

- packages/emd-basic-button/CHANGELOG.md
- packages/emd-basic-button/package-lock.json
- packages/emd-basic-button/package.json
Changelog and version bump are automatic.
> Release – Money Card 1.0.2

- packages/emd-basic-brand-icon/src/component/BrandIconView.js
> Release – Brand Icon v1.0.3

- package-lock.json
- packages/emd-basic-button/src/component/ButtonController.js
The click event could be listened directly on the button when it was disabled. This PR fixes that.
> Hot Fix – Fix click propagation [MASTER]

- package-lock.json
- packages/emd-basic-button/src/component/ButtonController.js
Hotfix – Fix click propagation [DEVELOP]
> Hot Fix – Fix click propagation [DEVELOP]

- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-brand-icon/src/component/BrandIcon.css
- packages/emd-basic-field/package-lock.json
This PR adds two new icons to the Brand Icons component: Cooper and Greencard.
> feat: Add Cooper and Greencard icons

- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-brand-icon/src/component/BrandIcon.css
- packages/emd-basic-field/package-lock.json
> Release – Brand Icon v1.2.0

- packages/emd-basic-icon/package-lock.json
- packages/emd-basic-icon/package.json
Payment icon to use.
Update emd assets version.
> feat: :tada: Update emd-assets version.

- packages/emd-basic-table/package-lock.json
- packages/emd-basic-table/package.json
- packages/emd-basic-table/public/index.css
- packages/emd-basic-table/src/component/Table.css
- packages/emd-basic-table/src/component/TableController.js
- packages/emd-basic-table/src/component/TableController.spec.js
- packages/emd-basic-table/src/component/TableView.js
This PR adds an adapter called `clickableadapter` that allows the user to define which table rows are clickable when `clickablerows` is on.
```
npm install
npm test
```
```
npm install
npm start emd-basic-table
```
> Feat – Conditional clickable rows on Table component

- packages/emd-basic-field-wrapper/src/component/FieldWrapperController.js
Release – Field Wrapper v1.0.3
> Release – Field Wrapper v1.0.3

- packages/emd-basic-field/src/component/FieldView.js
- packages/emd-basic-select/src/component/SelectController.js
- packages/emd-basic-select/src/component/SelectView.js
> Release – Field and Select

- packages/emd-basic-button/src/component/ButtonController.js
- packages/emd-basic-button/src/component/ButtonView.js
> Release — Button v1.2.0

- .eslintrc
- packages/emd-basic-field-wrapper/package-lock.json
- packages/emd-basic-field-wrapper/package.json
- packages/emd-basic-field/package-lock.json
- packages/emd-basic-field/package.json
- packages/emd-basic-field/src/component/FieldController.js
- packages/emd-basic-field/src/component/FieldController.spec.js
- packages/emd-basic-field/src/core.js
- packages/emd-basic-form/package-lock.json
- packages/emd-basic-form/package.json
- packages/emd-basic-form/public/index.js
- packages/emd-basic-pill-select/package-lock.json
- packages/emd-basic-pill-select/package.json
- packages/emd-basic-pill-select/src/component/PillSelectController.js
- packages/emd-basic-pill-select/src/core.js
- packages/emd-basic-select/package-lock.json
- packages/emd-basic-select/package.json
- packages/emd-basic-select/src/component/SelectController.js
- packages/emd-basic-select/src/component/SelectController.spec.js
- packages/emd-basic-select/src/core.js
Release — Field, Select, PillSelect and Form
> Release — Field, Select, PillSelect and Form

- package-lock.json
- packages/emd-basic-field-message/package-lock.json
- packages/emd-basic-field-message/package.json
- packages/emd-basic-field-wrapper/package-lock.json
- packages/emd-basic-field-wrapper/package.json
- packages/emd-basic-field/package-lock.json
- packages/emd-basic-field/package.json
- packages/emd-basic-field/src/component/Field.css
- packages/emd-basic-form/package-lock.json
- packages/emd-basic-form/package.json
- packages/emd-basic-pill-select/package-lock.json
- packages/emd-basic-pill-select/package.json
- packages/emd-basic-select/package-lock.json
- packages/emd-basic-select/package.json
- packages/emd-basic-select/src/component/Select.css
- Update `withFieldValidation` HOC to update validation events;
- Hide `[type=hidden]` fields;
- Correct space inside `emd-field`;
```
npm i && npm t
```
> Feat — Update validation events

- package-lock.json
- packages/emd-basic-field-message/package-lock.json
- packages/emd-basic-field-message/package.json
- packages/emd-basic-field-wrapper/package-lock.json
- packages/emd-basic-field-wrapper/package.json
- packages/emd-basic-field/package-lock.json
- packages/emd-basic-field/package.json
- packages/emd-basic-field/src/component/Field.css
- packages/emd-basic-form/package-lock.json
- packages/emd-basic-form/package.json
- packages/emd-basic-pill-select/package-lock.json
- packages/emd-basic-pill-select/package.json
- packages/emd-basic-select/package-lock.json
- packages/emd-basic-select/package.json
- packages/emd-basic-select/src/component/Select.css
> Release — Form components

- .storybook/config.js
- .storybook/style.css
- packages/emd-basic-button/README.md
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-card/README.md
- packages/emd-basic-card/src/component/Card.stories.js
- packages/emd-basic-icon/README.md
- packages/emd-basic-icon/src/component/Icon.stories.js
- packages/emd-basic-login/src/component/Login.stories.js
- packages/emd-basic-money/README.md
- packages/emd-basic-money/src/component/Money.stories.js
This release documents Button, Card, Input and Money.
> Release — Documents Button, Card, Input and Money

- package-lock.json
- package.json
Update semantic release (again) to version `16.0.x`. Let's see if this works. If not, I will hardcode version `15.9.x` again.
> Hotfix — Update semantic release (again)

- package-lock.json
- package.json
Update Semantic Release version (one more time)
> Hotfix — Update Semantic Release version (one more time)

- package-lock.json
- package.json
Add Husky and remove most npm security warnings.
```
npm i && npm t
```
> Hotfix — Add Husky and remove most npm security warnings

- package-lock.json
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-icon/package-lock.json
- packages/emd-basic-icon/package.json
- packages/emd-basic-icon/src/component/Icon.stories.js
Feature — Add Info Circle icon
```
npm i && npm start emd-basic-icon
```
```
```
> Feature — Add Info Circle icon

- package-lock.json
- package.json
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-icon/package-lock.json
- packages/emd-basic-icon/package.json
- packages/emd-basic-icon/src/component/Icon.stories.js
Release — Icon 1.6.0 and Brand Icon 1.4.0
> Release — Icon 1.6.0 and Brand Icon 1.4.0

- .storybook/config.js
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-card/src/component/Card.stories.js
- packages/emd-basic-icon/src/component/Icon.stories.js
- packages/emd-basic-login/src/component/Login.stories.js
- packages/emd-basic-money/src/component/Money.stories.js
- packages/emd-basic-tooltip/README.md
- packages/emd-basic-tooltip/public/index.css
- packages/emd-basic-tooltip/public/index.html
- packages/emd-basic-tooltip/src/component/Tooltip.css
- packages/emd-basic-tooltip/src/component/Tooltip.stories.js
- packages/emd-basic-tooltip/src/component/TooltipController.js
- packages/emd-basic-tooltip/src/component/TooltipView.js
Tooltip 1.1.0 and update other component's Storybook
> Release — Tooltip 1.1.0 and update other component's Storybook

- package-lock.json
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-icon/package-lock.json
- packages/emd-basic-icon/package.json
Update emd-assets version.
-
-
-
> feat: Update emd-assets version.

- package-lock.json
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-icon/package-lock.json
- packages/emd-basic-icon/package.json
- packages/emd-basic-state-wrapper/package-lock.json
Update assets version to 1.12.0
-
-
-
> Update emd-assets version to 1.12.0

- .storybook/config.js
- packages/emd-basic-button/README.md
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-card/src/component/Card.stories.js
- packages/emd-basic-login/src/component/Login.stories.js
- packages/emd-basic-money/src/component/Money.stories.js
- packages/emd-basic-pin-code/README.md
- packages/emd-basic-pin-code/package-lock.json
- packages/emd-basic-pin-code/package.json
- packages/emd-basic-pin-code/public/index.css
- packages/emd-basic-pin-code/public/index.html
- packages/emd-basic-pin-code/public/index.js
- packages/emd-basic-pin-code/src/component/PinCode.css
- packages/emd-basic-pin-code/src/component/PinCode.stories.js
- packages/emd-basic-pin-code/src/component/PinCodeController.js
- packages/emd-basic-pin-code/src/component/PinCodeController.spec.js
- packages/emd-basic-pin-code/src/component/PinCodeView.js
- packages/emd-basic-pin-code/src/core.js
- packages/emd-basic-pin-code/src/index.js
- packages/emd-basic-tooltip/src/component/Tooltip.stories.js
Implement the Pin Code component.
```
npm i && npm t
```
```
npm start emd-basic-pin-code
```
> Feature — Pin Code element

- packages/emd-basic-notification/src/component/Notification.stories.js
Micro PR to correct a code sample on Storybook.
> Hotfix — Correct Storybook code sample

- packages/emd-basic-notification/public/index.html
> Release Notification

- .storybook/config.js
- packages/emd-basic-slideshow/README.md
- packages/emd-basic-slideshow/package-lock.json
- packages/emd-basic-slideshow/package.json
- packages/emd-basic-slideshow/public/index.css
- packages/emd-basic-slideshow/public/index.html
- packages/emd-basic-slideshow/public/index.js
- packages/emd-basic-slideshow/src/component/Slideshow.css
- packages/emd-basic-slideshow/src/component/Slideshow.stories.js
- packages/emd-basic-slideshow/src/component/SlideshowController.js
- packages/emd-basic-slideshow/src/component/SlideshowController.spec.js
- packages/emd-basic-slideshow/src/component/SlideshowView.js
- packages/emd-basic-slideshow/src/core.js
- packages/emd-basic-slideshow/src/index.js
Release — Emerald Slideshow v1.0.0
> Release — Emerald Slideshow v1.0.0

- packages/emd-basic-slideshow/README.md
- packages/emd-basic-slideshow/src/component/Slideshow.css
- packages/emd-basic-slideshow/src/component/Slideshow.stories.js
- packages/emd-basic-slideshow/src/component/SlideshowController.js
- packages/emd-basic-slideshow/src/component/SlideshowController.spec.js
- packages/emd-basic-slideshow/src/component/SlideshowView.js
- packages/emd-basic-tooltip/src/component/TooltipController.js
- packages/emd-basic-tooltip/src/component/TooltipView.js
Release — Slideshow 1.1.0 and Tooltip 1.1.2
> Release — Slideshow 1.1.0 and Tooltip 1.1.2

- packages/emd-basic-brand-icon/README.md
- packages/emd-basic-button/README.md
- packages/emd-basic-card/README.md
- packages/emd-basic-icon/README.md
- packages/emd-basic-login/README.md
- packages/emd-basic-money/README.md
- packages/emd-basic-notification/README.md
- packages/emd-basic-pin-code/README.md
- packages/emd-basic-slideshow/README.md
- packages/emd-basic-tooltip/README.md
Improve documentation with installation and imports
> Feature — Improve documentation with installation and imports

- packages/emd-basic-brand-icon/CHANGELOG.md
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
Revert failed Semantic Release attempt:
This reverts commit cdb7527670c2964d39b20906ef43f5d359885de9.
> Fix — Revert failed Semantic Release attempt

- CODEOWNERS
- README.md
- package-lock.json
- package.json
- Add @eduardoborges as Code Owner
- Remove @julianasglasser as Code Owner
- Rename the package name from Sling to Emerald
- Update links in the documentation
> Feature — Update the repository's configuration

- packages/emd-basic-brand-icon/CHANGELOG.md
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
- packages/emd-basic-bullet/CHANGELOG.md
- packages/emd-basic-bullet/package-lock.json
- packages/emd-basic-bullet/package.json
- packages/emd-basic-table/package-lock.json
ci: Add debug flag to Semantic Release
> ci: Add debug flag to Semantic Release

- package-lock.json
- package.json
- packages/emd-basic-brand-icon/CHANGELOG.md
- packages/emd-basic-brand-icon/package-lock.json
- packages/emd-basic-brand-icon/package.json
> Force semantic release

- .releaserc.json
ci: Change release branches with array
> ci: Change release branches with array

- .travis.yml
- CODEOWNERS
- package-lock.json
- packages/emd-basic-brand-icon/README.md
- packages/emd-basic-button/README.md
- packages/emd-basic-card/README.md
- packages/emd-basic-drawer/public/index.css
- packages/emd-basic-drawer/public/index.html
- packages/emd-basic-drawer/src/component/Drawer.css
- packages/emd-basic-drawer/src/component/DrawerController.js
- packages/emd-basic-drawer/src/component/DrawerView.js
- packages/emd-basic-icon/README.md
- packages/emd-basic-login/README.md
- packages/emd-basic-money/README.md
- packages/emd-basic-notification/README.md
- packages/emd-basic-pin-code/README.md
- packages/emd-basic-slideshow/README.md
- packages/emd-basic-tooltip/README.md
This branch will become the new `master` branch, so it has to be updated to include all latest changes.
> Feature — Update branch emd-master

- .github/CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
chore: Replace Sling with Emerald
> chore: Replace Sling with Emerald

- .storybook/style.css
- packages/emd-basic-button/README.md
- packages/emd-basic-button/public/index.css
- packages/emd-basic-button/public/index.html
- packages/emd-basic-button/src/component/Button.css
- packages/emd-basic-button/src/component/Button.stories.js
- packages/emd-basic-button/src/component/ButtonController.js
- packages/emd-basic-button/src/component/ButtonView.js
- packages/emd-basic-button/src/core.js
> Release — Button v1.4.0 (ABC)

- packages/emd-basic-button/public/index.js
- packages/emd-basic-button/src/component/Button.css
Improves button behavior on touch devices:
- Prevents button text from being selected;
- Removes webkit tap highlight.
> feat: Improve button behaviour on touch devices

- packages/emd-basic-button/public/index.js
- packages/emd-basic-button/src/component/Button.css
> Release — Button v1.5.0

- packages/emd-basic-button/README.md
- packages/emd-basic-button/public/index.css
- packages/emd-basic-button/public/index.html
- packages/emd-basic-button/src/component/Button.css
- packages/emd-basic-button/src/component/Button.stories.js
Add small sized Button.
```
npm i && npm start emd-basic-button
```
```
```
> Feat — Small sized Button

- packages/emd-basic-loading-wrapper/.npmignore
- packages/emd-basic-login/.npmignore
- packages/emd-basic-notification/.npmignore
- packages/emd-basic-paginator/.npmignore
- packages/emd-basic-pill-select/.npmignore
- packages/emd-basic-pin-code/.npmignore
- packages/emd-basic-slideshow/.npmignore
- packages/emd-basic-tooltip/.npmignore
> Fix — Add .npmignore files
